### ISSUE TITLE
[JakartaONE Committee] Add THIS Repo to the JakartaONE website

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#15]
This repo and its content is the source of truth for all activity that makes a JakartaONE possible, as such the Repo needs to be in the website as a MUST item.

**Comment by cesarhernandezgt** [comment]
@aeiras current website has now a dedicated section to download a set of steps and requirements to engage the organization of a JakartaOne regional event.

![image](https://user-images.githubusercontent.com/1454523/111676933-4c759680-87e4-11eb-9301-b02130030c00.png)

Does the above accomplish the overall goal you shared within the context of this github issue?

**Comment by aeiras** [comment]
Hey Cesar, 

Thank you for the follow up, I appreciate it. :) 

Partially it does bring more transparency on how to participate. 
**Recommendations:**

- add the link of the JakartaONE repository to the below "download" call to action. Description can be:  Welcome to the JakartaONE Repo! If you want to provide feedback on the Hosting Your Own Regional JakartaONE, work on JakartaONEs, features that could improve the JakartaONE website, media pushes... etc, then you are in the right place to submit git tickets!

**Comment by cesarhernandezgt** [comment]
@aeiras 

Thank you for the suggestion. I notice that the pdf document has already the link to the https://github.com/jakartaee/jakartaone.org repository, in fact, the link automatically triggers the creation of a new Github issue in the jakartaone.org repository as the first step in the entire process (see attached image).

My opinion is that adding a second line right from the Download section in the Jakarta one website can add confusion to the user experience since if you click the link to the repository, then the user will not be able to read the well-documented process from the pdf. Currently having one point of information seems to be a better fit for those who are new to the process.

![image](https://user-images.githubusercontent.com/1454523/112547809-ddb6b100-8d80-11eb-90d7-d1bf93c5b57b.png)

**Comment by aeiras** [comment]
Actually it is nice you helped me navigate the PDF, Cesar. 
It is a good start. 

Request adjustments to the PDF guidelines:

-  MicroProfile name needs to be fixed. 
- Is there a public mailing list that can be created in addition to the "private" where the future and past communities can interact?  The Community forum is ok but with +850 people, it is time for JakartaONE to have its own public forum for communications. 

**Current Concerns**

- Organizing a JakartaONE takes 4months to get proper support. The Russia event is half of that. How does the marketing committee approved it and by cut written?
- I see lack of interaction to what it is written and what it is happening and I wonder why that is?   
- The reason why public jakartaone mailing list is needed is so that such a conversations and educating the global community interested in piloting such events come together and shape the process.

**Comment by cesarhernandezgt** [comment]
Thank you for the feedback @aeiras.

My feedback so far is that the original scope of this GitHub issue has diverged into JakartaOne website content and the overall process for preparing a JakartaOne event.

From your previous reply, it seems there are two potential Github Issues that need to be created in the https://github.com/jakartaee/jakartaone.org 

1. Update jakartaone-regional-events.pdf: Replace "Eclipse MicroProfile" with "MicroProfile".
2. Creation of public mailing list for JakartaOne organization events.

If you agree, please create the two tickets above in the https://github.com/jakartaee/jakartaone.org  repository, and then we can close this one since the original scope/request has been tackle already.

**Comment by aeiras** [comment]
Thank you, Cesar!
