### ISSUE TITLE
[ Media Collateral Resources] Publicly available is NEEDED

### ISSUE THREAD

**Issue by aeiras** [jakartaee/collateral#22]
- media designs cards

- example of written messages that can be pushed by the Community

- hashtags that are relevant by event

- speakers design cards that can be adjusted by speakers themselves- general use

- speaker's session templates to support speakers and normalized the event 

- enable local (by event continent ) JUGs to come together and help promote the event to its ecosystems. :) ---- THERE IS NO VALUE ON JAKARTAONE is those who are meant to benefit from the content shared are not the owners on the making of the event from day 1 of  the planning. 

 its presenters

- call to action on recommendations before & during the event

- add Community Resources Tab to the JakartaONE website ---- priority 1 so that the website holds all the information not only for speakers, organizers but also attendees. 

-

**Comment by cesarhernandezgt** [comment]
As of today, JakartaOne has the following resources and processes:

**Comment by aeiras** [comment]
Your follow-up, @cesarhernandezgt looks positive towards improvements in this area.

For inspiration, maybe the project could emulate the MicroProfile Branding page https://microprofile.io/resources/branding/

**Comment by cesarhernandezgt** [comment]
Thank you @aeiras for the feedback. My previos reply was under the context of JakartaOne events planing.
After seeing https://microprofile.io/resources/branding/  I think we already have this in Jakarat EE but not unified like MP does it.

If we take MP branding page as a baseline, the following is the number of clicks (pages or documents) one needs to have access to get the mp branding page:
- https://microprofile.io/
- - https://microprofile.io/resources 
- - - https://microprofile.io/resources/branding/

The following is an attempt to describe the hierarchy (the number of clicks ( pages or documents ) a Jakarta EE website visitor would need to follow to obtain many of the artifacts mentioned on the mp branding page:

Jakarta-ee-branding-guidelines.pdf 

- https://jakarta.ee/
- - https://jakarta.ee/about/faq/
- - - https://jakarta.ee/legal/trademark_guidelines/
- - - - https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-branding-guidelines.pdf 


Jakarta logo (artwork) download

- https://jakarta.ee/
- - https://jakarta.ee/about/faq/
- - - https://jakarta.ee/legal/trademark_guidelines/
- - - - https://jakarta.ee/legal/trademark_guidelines/jakarta-ee-branding-guidelines.pdf 
- - - - - https://www.eclipse.org/org/artwork/


Branding Materials (Jakarta EE Community Cards, Jakarta EE Presentation Template, etc)
- https://jakarta.ee/
- - https://jakarta.ee/resources

I propose to add the Jakarta branding guidelines and the artwork links to the Resource page Jakarta already has:
https://jakarta.ee/resources since this will provide the same information as MP branding page at the same number (levels) of clicks to navigate.

Let me know your feedback, and I'll be happy to open a GitHub issue on Jakarta Website for the improvement.

**Comment by aeiras** [comment]
@cesarhernandezgt, 

Your feedback improves what currently is as it simplifies it and makes the visitor navigate the website much more fluidly. +1 .

**Comment by cesarhernandezgt** [comment]
Closing this in favor of: https://github.com/jakartaee/jakarta.ee/issues/1595
