### ISSUE TITLE
[Primeton quote]

### ISSUE THREAD

**Issue by laliwa** [jakartaee/collateral#36]
Primeton takes it of great importance that we take part in the process of promoting Jakarta EE especially in China and also participating in the specifications developing procedure. By leveraging the advantages of the new features of Jakarta EE like cloud-native, microservice, and other exciting improvements, we can always keep our customers convinced that we are a forward-looking company to speed up their digital transformation process.

- Scott Wang, VP of Primeton, Software Development

**Comment by aeiras** [comment]
Eric, 

What do you think about below items? 
They are suggestions that can take any shape. :) 

- **Issue ticket** : https://github.com/jakartaee/collateral/issues

- **Subject ticket:** [Org Name]  Submission of Membership Quote

- **Quote answers:** Why are you investing the time and resources on Jakarta EE ecosystem? 

- **Author:** Name - Title- Company  

1. On Author, I would like for the quotes to add the capability to either add the Author's git account hiperlink or twitter or regular bio- media choice provided by the Author.

**Comment by aeiras** [comment]
- **quote length**: currently, 3 quotes rotate, so space is about 2 to 4 sentences. If you want to add a word count, that could help keep the quote concise as well.  I am too simple and say 2 to 3 sentences, but that is not helpful with running sentences, so I think you can help improve that item. :) 

Cheers, and thank YOU for being awesome!

**Comment by laliwa** [comment]
> * currently, 3 quotes rotate, so space is about 2 to 4 sentences. If you want to add a word count, that could help keep the quote concise as well.  I am too simple and say 2 to 3 sentences, but that is not helpful with running sentences, so I think you can help improve that item. :)

among the 3 quotes, I take the IBM version as the standard, its length is in the middle of the 3, it has 66 words in total, so I think 60 maybe a reasonable count.

**Comment by laliwa** [comment]
> Eric,
> 
> What do you think about below items?
> They are suggestions that can take any shape. :)
> 
> * **Issue ticket** : https://github.com/jakartaee/collateral/issues
> * **Subject ticket:** [Org Name]  Submission of Membership Quote
> * **Quote answers:** Why are you investing the time and resources on Jakarta EE ecosystem?
> * **Author:** Name - Title- Company
> 
> 1. On Author, I would like for the quotes to add the capability to either add the Author's git account hiperlink or twitter or regular bio- media choice provided by the Author.

Sounds great to me.  :)

**Comment by aeiras** [comment]
Eric, 

Thank you for brainstorming with me to push the quote guidelines. :) [Quote Submission Guidelines](https://docs.google.com/document/d/1SWnFtcTvAkWMThN1uE2KKn7WV6i3SFVetSa4YlSBhsk/edit#) Currently housed under the Jakarta EE Community drive under the "Photos" folder. 

Because of your collaboration, I will send a follow-up to the WG thread to update this initiative. So much!  :) 

Now, using your 60-word count, I took the liberty to adjust your submitted quote to:
"_Primeton takes it of great importance that we take part in promoting Jakarta EE, especially in China, and participating in the specifications developing procedure. By leveraging the advantages of Jakarta EE's new features like cloud-native, microservice, and other exciting improvements, we can always keep our customers convinced that we are a forward-looking company to speed up their digital transformation process._" 

Please drop the adjustments as you see fit. :) Thank you for making it fun Eric, I appreciate your time and help!

**Comment by aeiras** [comment]
@laliwa can you check the Quote Submission Guidelines as well. Anyone on the web has edit access. :) 
Ideally, the Marketing Committee pushed for using Git pages for housing this and other marketing guidelines so that anyone in the Community can help adjust the documentation via PR submissions. Wiki via git is a horrible way to enable others to help with documentation. 
On the TCK side of things, we have dropped the usage of wiki pages and moved 100% to pages, it is formidably friendly and welcoming to anyone who wants to help. Scalable as well.

**Comment by laliwa** [comment]
Great Amelia!


LGTM! I don't think I need to change anything, thanks a lot for taking the trouble to optimize it.&nbsp;






------------------

  			 				普元信息技术股份有限公司
 				
科创板上市企业（股票代码688118）
专注于：微服务，DevOps，大数据，云计算，移动架构
                 
 				
 									 					孟庆余
 					市场部市场总监
 					
 					 						电话&nbsp;010-62698005&nbsp; 						手机&nbsp;13811302857
 						传真&nbsp;010-62698015&nbsp; 						邮箱&nbsp;mengqy@primeton.com
 						http://primeton.com 					
 				
 										 						
 						关注获取行业案例分享，普元一手官方资讯
（微信号Primeton-Software）
 						
	 						
 						关注获取前瞻技术理念，普元产品技术分享
（微信号EAWorld）
 				 				
 			
 			
 			
 			 		
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by cesarhernandezgt** [comment]
@aeiras is there an email thread behind these quotes? 
I'm trying to identify where all these quotes submitted in the collateral repository will finally be published? website?

**Comment by aeiras** [comment]
Hola Cesar, 

Yes, Oct 21st WG email [thread ](https://www.eclipse.org/lists/jakarta.ee-wg/msg00473.html)

They ought to be published under the WG page in the website. 
My recommendation is for the project to emulate and likely improve what is currently operational for [MPWG page](https://microprofile.io/workinggroup/). The guidelines for MPWG quotes welcomed everyone, as so do the Jakarta EE Quote. It is the job of the marketing committee to decide how, who, etc. Also note that the quote submission guidelines have been converted to wiki and it welcomes MicroProfilers PRs, that means, the document moved into the project's repo. I recommend such a collaborative documentation that welcomes others beyond the cmtee to be placed in the project's website and added to the repo. INFRA matters greatly and it ought to align with open source mentality.

**Comment by TanjaObradovic** [comment]
@cesarhernandezgt can you please guide @laliwa to do the same as with  Jelastic quote? This is logged in at the wrong place. Many thanks!

**Comment by cesarhernandezgt** [comment]
Hi @laliwa 

I created a small guide to enable you to submit the quote in the right place for the jakarta ee website. The guide is a work in progress, this I the current version available in my PR:
https://github.com/jakartaee/jakarta.ee/blob/292ee6c1b8e610ec8f84977ccce5f79cfc3e7fd8/HOWTOS.md

Feel free to close this issue so any follow-up can be handled in the https://github.com/jakartaee/jakarta.ee repository and also pull me in case further troubleshooting is needed it.

**Comment by cesarhernandezgt** [comment]
Closing this since the website was updated back in late 2021
